### ISSUE TITLE
Host SLA is wrong since 19th May and I cannot find why.

### ISSUE THREAD

**Issue by BornTKill** [Icinga/icingaweb2-module-reporting#71]
## Describe the bug

Since fews months, SLA for running host became wrong. May be an issue with my icinga2 DB but cannot find what/where.

## ScreenShots

![image](https://user-images.githubusercontent.com/16973237/92381698-9e3db580-f10b-11ea-84da-a162c3df9470.png)

Action on Icinga Director for the period.

![image](https://user-images.githubusercontent.com/16973237/92382246-96324580-f10c-11ea-9eb8-d9e3bbf8b555.png)

## Your Environment

* Module version: 9.0.2
* Dependent module versions: React Bundle 0.7.0, IPL v0.3.0, PDFexport 0.9.1
* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: Safari/Firefox/Chrome
* Icinga 2 version used (`icinga2 --version`): 2.11.2-1.bionic
* PHP version used (`php --version`): PHP 7.2.24
* Server operating system and version: Ubuntu  18.04.3 LTS

Thank you for your help.

**Comment by KaiserSoft** [comment]
We have the same problem after we had a storage failure. It looks like our hosts generated a "down" event but the the "Ping OK" was never added to the database.

**BACKUP your DB if you try this**

Here is how I fixed it

1. Check the History for your host using the WebUI. As you can see the host failed to generate the "all clear" event.
![webUI-error](https://user-images.githubusercontent.com/2138606/125265050-bcb0a680-e304-11eb-9d6e-4043317d8b65.PNG)

2. First you need to get the host_object_id from the DB
`select host_id,host_object_id,display_name from icinga_hosts WHERE display_name LIKE "%YOURHOSTNAME%";`
3. Check 'icinga_statehistory' table for entries for this server. Use the host_object_id from the previous step
`SELECT * FROM icinga_statehistory WHERE object_id = YOURHOSTOBJECTID ORDER BY state_time DESC LIMIT 50`
4. If the errors from Step 1 are the most recent entries then you should see your error events towards the top.
As you can see the previous errors all have a "PING OK" entry. So let's fake one.
![DB-host-events](https://user-images.githubusercontent.com/2138606/125265043-bb7f7980-e304-11eb-819c-aad076765b06.PNG)
5. **WARNING** the following step may corrupt your DB.
I am using the values from the last "PING OK" entry from my DB as I don't know what the variables do. 
YOURENTRYTIME is "state_time" I use the value from the last fail entry + 1 second, like 2021-04-21 21:27:32
YOURHOSTOBJECTID is the host object_id from Step 2
IDOFOK is the statehistory_id of the past "Ping OK" message for this host
`INSERT INTO icinga_statehistory (instance_id, state_time, state_time_usec, object_id, state_change, state, state_type, current_check_attempt, max_check_attempts, last_state, last_hard_state, output, long_output, check_source, endpoint_object_id)
SELECT instance_id, 'YOURENTRYTIME', state_time_usec, 'YOURHOSTOBJECTID', state_change, state, state_type, current_check_attempt, max_check_attempts, last_state, last_hard_state, output, long_output, check_source, endpoint_object_id
FROM icinga_statehistory
WHERE object_id = 'YOURHOSTOBJECTID  ' AND ((statehistory_id = 'IDOFOK'));`
6. Check your host again. The "History Tab" now has the "Ping OK" entry and your SLA reports should be green again.
![DB-ok](https://user-images.githubusercontent.com/2138606/125265049-bc181000-e304-11eb-95d9-0b4077fabcb3.PNG)

![webUI-error-fixed](https://user-images.githubusercontent.com/2138606/125265052-bcb0a680-e304-11eb-80d9-5bf7a22a60dd.PNG)

**Comment by yhabteab** [comment]
When this issue still occurs, please reopen this and describe your problem in detail and include step-by-step instructions on how to reproduce it. `Report`, `schedule` configs, etc. Looking at the posted screenshot, I can't tell what the problem is.
